---
title: "Profitability Analysis"
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: true
    df_print: kable
    math_method:
      engine: mathjax
---

# Overview

The Profitability Analysis module enables users to assess the economic benefits of land-use change scenarios by calculating Net Present Value (NPV). It evaluates both financial and environmental impacts, helping to identify trade-offs between economic development and environmental sustainability.

# Key Concepts:

1. **Net Present Value (NPV)**: A financial metric that calculates the current value of future cash flows generated by a project or investment, accounting for the time value of money. It helps assess the profitability of different land-use scenarios.

<!-- 2. **Opportunity Cost**: The potential benefits lost when choosing one land-use option over another. This concept highlights the trade-offs between economic development and environmental sustainability. -->

<!-- 3. **Carbon Emissions**: The release of carbon dioxide (CO2) and other greenhouse gases associated with various land-use practices. Understanding carbon emissions is essential for evaluating environmental impacts and developing strategies for mitigation. -->

2. **Economic Benefits**: The financial gains derived from land-use changes, encompassing revenue generation, cost savings, and potential investments in sustainable practices. This analysis aids decision-makers in balancing economic and environmental goals.

# Data and Input Variables

Before using the Profitability Analysis tool, prepare the following:

1. **Land Cover Maps First Year**: A categorical raster file in GeoTIFF format representing land use types for the start year. This file must have the UTM projection system.

2. **Land Cover Map Second Year**: A categorical raster file in GeoTIFF format representing land use types for the end year, also using the UTM projection system.

3. **NPV Lookup Table**: A CSV file containing numerical data that outlines the revenue stream and cost structure for each land use type. This table provides the Net Present Value (NPV) of various land uses.

4. **QUES-C Lookup Table**: A CSV file with numerical data on carbon stocks. This database includes carbon values (CO2eq) associated with different land use types.

## Using the Profitability Analysis Module

Follow these steps to use the module:

<video controls style="max-width:80%;height:auto;">
    <source src="ta-profit.mp4" type="video/mp4">
    Your browser does not support the video tag.
</video>

# Accessing Outputs

After the analysis completes, you'll find the following in your selected output directory:

1. **NPV Distribution Map First Year**: A binary raster map in GeoTIFF format, derived from the land cover map. It highlights user-defined focal area classes, where focal areas are represented by a value of 1, showing the areas of interest for carbon analysis during the first year.

2. **NPV Distribution Map Second Year**: A binary raster map in GeoTIFF format, derived from the land cover map. It highlights user-defined focal area classes, where focal areas are represented by a value of 1, showing the areas of interest for carbon analysis during the second year.

<!-- 3. **Emission Map**: A raster-based representation of emission data, using a polygon shapefile of sampling grids. These grids are utilized to extract key values related to TECI and focal area size, which contribute to understanding emissions linked to land use changes. -->

<!-- 4. **Opportunity Cost Map**: A raster plot representing the Degree of Integration of Focal Area (DIFA) Index. The x-axis shows the Total Edge Contrast Index (TECI), while the y-axis displays the cumulative proportion of the focal area. The curve illustrates the relationship between habitat fragmentation (TECI) and habitat amount, with the area under the curve determining the DIFA score (ranging from 0 to 100%). Higher DIFA scores indicate better habitat integration. -->

3. **Profitability Analysis Report**: An HTML report summarizing the profitability analysis results. It includes key interpretations and visualizations of outputs, such as carbon, emission, and opportunity cost maps, offering insights into both the economic and environmental impacts of land use changes.

---

For more detailed information or troubleshooting, refer to the full Profitability Analysis documentation here https://help.lumens.or.id/07-profitability.html or contact the tool developers.

<font size="1">LUMENS is free software and comes with ABSOLUTELY NO WARRANTY. Users are responsible for the results generated. Results depend on the quality of the input data ("garbage in, garbage out") and may vary or be sensitive to the parameters used. Please report any problems encountered while using LUMENS as [a GitHub issue](https://github.com/icraf-indonesia/lumens-shiny/issues). Feedback and questions are welcome [Contact Us URL].</font>