---
title: "Planning Unit Reconciliation (Reconcile) Quick Guide"
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: true
    df_print: kable
---

# Overview

Planning unit reconciliation is a process to resolve overlapping permits by referring to function reference maps. Reconciliation is done by analyzing how well the permit data matches the reference data.

# Data Preparation

1. Unresolved Case Map (Shapefile format)
   
   - Shapefile of overlayed planning units with some layer that conflict, defined as unresolved case.
   
2. Unresolved Case Attribute (Excel format)
   
   - Detailed unresolved case table .Before running PUR Reconcile module, the reconcile action (drop-down selection) on 'PUR_unresolved_case.xlsx' need to be defined. You can use Microsoft Excel or any free spreadsheet software (e.g. Google Sheet) to do it

# Using The Module

Follow these steps to use the module:

1. **Unresolved Case Map**
   - Click "Browse" and select your Unresolved Case Map shapefile.

2. **Unresolved Case Attribute**
   - Click "Browse" and select your excel file containing the table of reconcile action

5. **Output Directory**
    -   Click "Select Output Directory" to choose where results will be saved.
    
6.  **Run Analysis**
    -   Click "Run PUR Reconcile" to start the process.
    
7.  **View Results**
    -   View the analysis report and output files.

# Accessing Outputs

After the analysis completes, you'll find the following output data in your selected output directory:

- Planning Unit Reconcile (Shapefile)

- Reconciled Class Attribute Result (CSV) 

- **PUR Reconcile Report**: An HTML file providing an overview of the analysis results, including:

    -   Data visualisation on input data
    -   Data visualisation on planning unit reconciliation result
    -   Descriptive statistics resolved case of planning units
    
------------------------------------------------------------------------

For more detailed information or troubleshooting, refer to the full QuES-H documentation or contact the tool developers.

<font size="1">LUMENS is free software and comes with ABSOLUTELY NO WARRANTY. Users are responsible for the results generated. Results depend on the quality of the input data ("garbage in, garbage out") and may vary or be sensitive to the parameters used. Please report any problems encountered while using LUMENS as [a GitHub issue](https://github.com/icraf-indonesia/lumens-shiny/issues). Feedback and questions are welcome [Contact Us URL].</font>