---
title: "QuES-B Quick Guide"
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: true
    df_print: kable
---

```{r kableExtra, include=FALSE}
library(kableExtra)
options(knitr.table.format = "html")
```


# Overview

QuES-B (Quantification of Environmental Services on Biodiversity) analyzes biodiversity conditions at the landscape scale by calculating the Degree of Integration of Focal Area (DIFA) Index, focusing on the composition and configuration of focal areas.


# Key Concepts

1. **Focal Area**: Habitats of taxa of interest or areas with high biodiversity. Users define these by selecting specific land cover classes.
   
2. **TECI Map**: Illustrates the spatial distribution of focal area fragmentation and integration across the landscape by measuring the contrast between adjacent land cover types.
   
3. **DIFA Index**: Quantifies how well integrated a focal area is within a landscape, indicating its functionality to maintain biodiversity through gene exchange and migration in the face of environmental changes.

# Data and Input Variables

Before using the QuES-B Analysis tool, prepare the following:

1. **Land Cover Maps**: A raster file of current land use/land cover (LULC) in GeoTIFF format. This must be in GeoTIFF format with the relevant UTM projection system.
   
2. **Land Use/Cover & Focal Area Lookup Table**: A CSV file describing raster values with their corresponding land cover classes. Users define focal areas by selecting specific land cover classes. Please refer to the manual and example data for the correct column arrangement.
   
3. **Edge Contrast Table**: An FSQ file defining edge contrast between land cover types.
   
4. **Sampling Points**: A number of sampling points (default is 1000). This is used to generate sampling grids for calculating DIFA. A higher number provides finer DIFA estimation but requires more computing time and resources.
   
5. **Window Size**: The size of the moving window for analysis in meters (default is 1000). Window size represents the dispersal radius, a threshold for ecological connectivity, assuming that taxa associated with the focal area can typically move or disperse up to this distance.
   
6. **Window Shape**: The shape of the moving window (default is Square). A circular shape is more realistic but requires more computing resources and time.
   
7. **FRAGSTATS Configuration (Optional)**: A default file will be used if not specified. Refer to the manual for further details.
   
8. **FRAGSTATS Path (Optional)**: A custom path to the Fragstats directory installed on your PC if Fragstats is installed in a custom installation directory. The default path will be used if not specified, assuming the default Fragstats installation directory.



`r text_spec("Important", background = "#D05A6E", color = "white", bold = T, font_size=20)`



> <font size="2">Before running the QuES-B module, ensure that you have downloaded and installed the latest Fragstats software. Fragstats is a spatial pattern analysis program used in QuES-B for calculating the degree of integration of focal areas to the surrounding land use and land cover types. **We strongly recommend installing Fragstats in the default working directory to ensure compatibility with LUMENS software.** You can download the latest version (2024-May-07) [**here**](https://www.fragstats.org/download/frg4.3.833b%5B64%5D.zip). For further description, please visit the [Fragstats Documentation](https://www.fragstats.org/index.php/documentation).</font>



## Using the QuES-B Module

Follow these steps to use the module:

<video controls style="max-width:80%;height:auto;">
    <source src="quesb.mp4" type="video/mp4">
    Your browser does not support the video tag.
</video>

# Accessing Outputs

After the analysis completes, you'll find the following in your selected output directory:

1. **Focal Area Map**: A binary raster map in GeoTIFF format derived from the land cover map, displaying the user-defined focal area classes represented as 1.
   
2. **TECI Map**: A raster map in GeoTIFF format illustrating the spatial distribution of focal area fragmentation and integration across the landscape. It measures the contrast between adjacent land cover types. Lower TECI values indicate well-integrated areas with minimal contrast between adjacent land cover types. Conversely, higher TECI values represent more segregated areas with greater contrast between neighboring land uses. Gray areas represent regions outside the dispersal threshold from the focal area.
   
3. **Sampling Grid**: A polygon shapefile of sampling grids used to extract values of TECI and focal area size.
   
4. **DIFA Plot**: A plot illustrating the Degree of Integration of Focal Area (DIFA) Index, which measures how well the focal habitat is integrated within the landscape. The x-axis represents the Total Edge Contrast Index (TECI), while the y-axis shows the cumulative proportion of the focal area. The curve depicts the relationship between habitat fragmentation (TECI) and habitat amount. The area under this curve determines the DIFA score, ranging from 0 to 100%. Higher scores indicate better habitat integration.
   
5. **QuES-B Report**: An overview of the analysis results in HTML format, providing brief interpretations and visualizations of these outputs.

---

For more detailed information or troubleshooting, refer to the full QuES-B documentation or contact the tool developers.

<font size="1">LUMENS is free software and comes with ABSOLUTELY NO WARRANTY. Users are responsible for the results generated. Results depend on the quality of the input data ("garbage in, garbage out") and may vary or be sensitive to the parameters used. Please report any problems encountered while using LUMENS as [a GitHub issue](https://github.com/icraf-indonesia/lumens-shiny/issues). Feedback and questions are welcome [Contact Us URL].</font>
